export enum IconName {
  EMAIL = "mail",
  LOCK = "lock",
  EDIT = "edit",
  CIRCLE = "circle",
  LIKE = "favorite",
  CHAT = "chat-bubble-outline",
  SAVE = "turned-in-not",
  PROFILE = "account-circle",
  POST = "edit",
  THREAD = "chat-bubble",
  SCHOOL = "school",
  ACCESSIBILITY = "accessibility",
  FLAG = "flag",
  CONTACT = "import-contacts",
  ARROW_BACK = "arrow-back",
  COIN = "monetization-on",
  CHECK = "check",
  CLOSE = "close",
}
