export enum ScreenName {
  WELCOME = "welcome",
  SIGN_UP = "signUp",
  SIGN_IN = "signIn",
  WRITE_BODY = "writeBody",
  SELECT_HASHTAG = "selectHashTag",
  HOME = "home",
  NEW_POST = "newPost",
  MAIN = "main",
  CREATE_POST = "createPost",
  PLACEHOLDER = "placeholder",
  SEARCH = "search",
  NOTIFICATION = "bell",
  PROFILE = "user",
  PROFILE_MAIN = "profileMain",
  PROFILE_EDIT = "profileEdit",
  SETTING = "setting",
  SETTING_MAIN = "settingMain",
  SETTING_ACCOUNT = "settingAccount",
  SETTING_MUTE_ACCOUNT = "settingMuteAccount",
}
